global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'users-service'
    static_configs:
      - targets: ['host.docker.internal:8002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'workouts-service'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s
